### ISSUE TITLE
FRONTEND - Create Sign In / Register && Profile

### ISSUE THREAD

**Issue by vivilenard** [RealConrad/42transcendence#16]
1. Create it on Figma
2. Actually code it

**Comment by kglebows** [comment]
The idea is:
1. It will use Bootstrap so we can actually gain points for that module.
2. It will be in different, modern and contrasting to the main theme style.
3. It will be displayed on above, visually distinct layer.
4. Could be displayed as popup window centered on view port.
5. Cannot be bigger than Game Area (calculated in CSS and minimum 720x1280).
6. It will be accessed by distinctive call to action buttons from main layer. 
![image](https://github.com/user-attachments/assets/9746f0ba-0ff0-405e-b690-64aae65cb059)
7. Exiting top layer via button (suggestion)
![image](https://github.com/user-attachments/assets/63b76fbe-d647-400a-9cce-5c5fde454c2b)
8. The purpose of this layer will be to handle all fancy backend stuff like:

- Profile view
- Chat (if implemented)
- Match History
- Player Statistics (@PetruCazac @RealConrad @harshkumbhani - what we can store and get from DB ?)
- Achievements (if implemented)
- Search functions
- ... (What else we could do there ? @PetruCazac @RealConrad @harshkumbhani @vivilenard )

**Comment by RealConrad** [comment]
Feels weird to display match history/player statistics on a modal? Why dont we just display it on the "right hand side"? Maybe im misunderstanding the design?


We dont currently have any API's to store/fetch game data, but yes - eventually I will create it (once game logic works decent enough)


Also, do not have 2 separate buttons for "signup" and "signin". Just make it 1 button "Sign-in" and from there the user can register or login. This is a standard across many sites. For instance this how youtube looks like if your not signed in:
<img width="2046" alt="image" src="https://github.com/user-attachments/assets/b7f0f4ce-4344-464f-a362-9e698803b8bb">
