### ISSUE TITLE
When speed is to high, the ball can fly through paddle

### ISSUE THREAD

**Issue by kglebows** [RealConrad/42transcendence#57]
Annoying bug,
tried to fix it but i did not find a working solution.
I think the problem is with collision checking. calculated ball X skips paddle.

**Comment by RealConrad** [comment]
Will try to find a fix for it on Saturday.


This is needed to be fixed for eval

**Comment by RealConrad** [comment]
Will try to find a fix for it on Saturday.


This is needed to be fixed for eval

**Comment by RealConrad** [comment]
Did not reproduce this bug. Marking it as complete
