### ISSUE TITLE
FRONTEND - Design a UI

### ISSUE THREAD

**Issue by RealConrad** [RealConrad/42transcendence#6]
Design a UI for the project.

Some things to consider:
- Colour scheme
- Create a UI thats accessible visually impaired users
- Create something nice to look at pls. dont make it look like a 1993 website. thanks <3 
- Smooth transitions (e.g. smooth button effects when hovering over them etc)
- Is this possible to build with Bootstrap components?
- Will we need to make our own components with CSS/JS?

 Mandatory pages that will be needed:
- [ ] Login/Register page
- [ ] Home page
- [ ] Profile page
- [ ] Tournament page
- [ ] Gameplay page
- [ ]  Anything else that you think would be needed

Some UI components that will be needed:
- [ ] Navbar
- [ ] Popup model?
- [ ] Login/Registration forms
- [ ] Buttons
- [ ] Anything else that you think is needed
- [ ] Add an option to change languages

**Comment by vivilenard** [comment]
#Colors:

- black / dark blue background
- whiteish font
- would suggest 2 more colors ? Maybe pink and yellow
![colorpalette](https://github.com/RealConrad/42transcendence/assets/78664024/c72bdf40-48e2-428a-8644-1da9bef58f76)
