### ISSUE TITLE
UI font fix for login

### ISSUE THREAD

**Issue by kglebows** [RealConrad/42transcendence#63]
![image](https://github.com/user-attachments/assets/98fada47-2aa6-4295-a4d8-7178b8db1649)

Descriptive text should use the same font as on the HowTo? page.  The Player2 font is cool but if its only one used its turning really kitschy. 

The general rule should be -> Highlight elements text, like titles, names, focus points - should use Player2 font, all the rest - the secondary elements, descriptions, info -> should use the font used in HowTo? (image). 
And least important elements, like log, or whatever, should be with lower opacity or gray colour - but i dont think we have any of those.
That way we have only 3 levels of text for UI and only 2 fonts used. This is the way.
![image](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExeGhkNWVjZXR4Nm12czR2NG15dnNnYjFpOHR0dmUwenBucWlxZG5tbiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/6UFgdU9hirj1pAOJyN/giphy.gif)

**Comment by RealConrad** [comment]
Will add a fix on Saturday as it's a 1 line change and won't take long
